inputs:
  codecov_token:
    description: Codecov secret token
    required: true

runs:
  using: composite
  steps:
    - uses: colcon/ci/.github/workflows/pytest.yaml@main
      env:
        CODECOV_TOKEN: ${{ inputs.codecov_token }}
