---
name: Run tests

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  pytest:
    uses: ./.github/workflows/pytest.yaml
    with:
      prerun-step: 'cargo install --git https://github.com/luca-della-vedova/cargo-ament-build.git --branch luca/binaries_on_windows'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
