---
name: Run tests

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  pytest:
    uses: luca-della-vedova/ci/.github/workflows/pytest.yaml@add_init
    with:
      prerun-step: 'cargo install cargo-ament-build'
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
